language: node_js

sudo: required

node_js:
  - '10'

os: linux

install:
  - yarn

script:
  - npm run lint

before_deploy:
  - npm run build && cd ./examples && yarn && npm run build

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
  - provider: pages
    local_dir: ./examples/dist
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    on:
      branch: master

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

cache:
  yarn: true
